### ISSUE TITLE
As a user, I need to setup a base component that shows a webcam icon over the cardboard icon

### ISSUE THREAD

**Issue by labofoz** [labofoz/aframe-seeclarke#1]
## Overview
Let's start by creating a component on the scene object.

![image](https://user-images.githubusercontent.com/41490928/43927605-f0a85a8a-9be2-11e8-8f2a-1808419b3c89.png)

## Tasks
- [x] Setup the repository
- [x] Create the main entry point
- [x] Create a dummy scene
- [x] Add a `headtracking` component (don't actually code it yet)

**Comment by labofoz** [comment]
Completed:
![image](https://user-images.githubusercontent.com/41490928/43987547-3577ea0a-9cd7-11e8-8060-ce69c23ab82b.png)
